# Copy this file to create default config
#
# cp config_example.toml config.toml

CoverImageDir = ""
Debug = false
MaxImageID = 0
NormalFont = ""
ORLYFont = ""
Port = ""
QueueLen = 10
TitleFont = ""
Width = 800
WorkerNum = 4
